cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mentor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', include('register.urls'), name="register"),
    path('courses/', include('courses.urls'), name="courses"),
    path('cart/', include('cart.urls'), name="cart"),
    path('orders/', include('orders.urls'), name="orders"),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from courses.models import LopHoc
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(LopHoc, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])

    return redirect('cart:cart_detail')


@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(LopHoc, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'], 'override': True})
    username = request.session.get('username', 0)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block titleblock %}
<title>LEAP - Thanh toán</title>
{% endblock %}

{% block bodyblock %}
<div class="breadcrumbs" data-aos="fade-in">
  <div class="container">
    <h2>Thông tin thanh toán</h2>
    <p>
      Sau đây là danh sách các khóa học đang chờ thanh toán.
    </p>
  </div>
</div>
<!-- Shopping Cart -->
<div class="shopping-cart section">
	<div class="container" style="margin-top: 100px;">
		<div class="row">
			<div class="col-12">
				<!-- Shopping Summery -->
				<table class="table shopping-summery">
					<thead>
						<tr class="main-hading">
							<th>TÊN LỚP</th>
							<th>HỌC PHÍ (đ)</th>
							<th>SỐ HỌC SINH</th>
							<th>TỔNG</th>
							<th><i class="ti-trash remove-icon"></i></th>
						</tr>
					</thead>
					<tbody>
						{% for item in cart %}
						{% with product=item.product %}
						<tr>
							<td class="product-des" data-title="Description">
								<p class="product-name">{{product.ten_lop}}</p>
							</td>
							<td class="price" data-title="Price"><span>{% load humanize %}{{product.price|floatformat:0|intcomma}} VNĐ</span></td>
							<td class="qty" data-title="Qty">
								<!-- Input Order -->
								<div class="input-group">
									<form action="{% url 'cart:cart_add' product.id %}" method="POST">
										{{item.update_quantity_form.quantity}}
										{{item.update_quantity_form.override}}
										{% csrf_token %}
										<input type="submit" value="&#x21bb;">
									</form>
								</div>
								<!--/ End Input Order -->
							</td>
							<td class="total-amount" data-title="Total"><span>{% load humanize %}{{item.total_price|floatformat:0|intcomma}} VNĐ</span></td>
							<td class="action" data-title="Remove">
								<form action="{% url 'cart:cart_remove' product.id %}" method="POST">
									{% csrf_token %}
									<input type="submit" value="&#9746;">
								</form>
							</td>							
						</tr>
						{% endwith %}
						{% endfor %}
					</tbody>
				</table>
				<!--/ End Shopping Summery -->
			</div>
		</div>
		<div class="row">
			<div class="col-12">
				<!-- Total Amount -->
				
					<div class="row">
						<div class="col-lg-8 col-md-5 col-12">
              <h5 style="margin-top: 30px;">Quyền lợi mua nhóm:</h5>
              <ul>
                <li>Nhóm 2 người: giảm 5%</li>
                <li>Nhóm 3 người: giảm 10%</li>
                <li>Nhóm 4 người trở lên: giảm 15%</li>
              </ul>
						</div>
						<div class="col-lg-4 col-md-7 col-12" style="margin-top: 25px;margin-bottom:25px">
              <div class="total-amount">
              <div class="right">
								<ul>
									<li>Tạm tính: <span class="tab">{% load humanize %}{{cart.get_sum|floatformat:0|intcomma}} đ</span></li>
									<li>Bạn được giảm: <span class="tab">{% load humanize %}{{cart.discounted_price|floatformat:0|intcomma}} đ</span></li>
									<li class="last">Tổng đơn hàng: <span class="tab">{% load humanize %}{{cart.get_total_price|floatformat:0|intcomma}} đ</span></li>
								</ul>
								<div class="button5">
									<a href="{% url 'orders:order_create' %}" class="btn get-started-btn">Thanh toán</a>
								</div>
              </div>
							</div>
            </div>
					</div>
				
				<!--/ End Total Amount -->
			</div>
		</div>
	</div>
</div>
<!--/ End Shopping Cart -->

<style>
body {
  font-family: 'open sans';
  overflow-x: hidden; }

img {
  max-width: 100%; }

span.tab{
  position: absolute;
  right: 10%;

}
.preview {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }
  @media screen and (max-width: 996px) {
    .preview {
      margin-bottom: 20px; } }

.preview-pic {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.preview-thumbnail.nav-tabs {
  border: none;
  margin-top: 15px; }
  .preview-thumbnail.nav-tabs li {
    width: 18%;
    margin-right: 2.5%; }
    .preview-thumbnail.nav-tabs li img {
      max-width: 100%;
      display: block; }
    .preview-thumbnail.nav-tabs li a {
      padding: 0;
      margin: 0; }
    .preview-thumbnail.nav-tabs li:last-of-type {
      margin-right: 0; }

.tab-content {
  overflow: hidden; }
  .tab-content img {
    width: 100%;
    -webkit-animation-name: opacity;
            animation-name: opacity;
    -webkit-animation-duration: .3s;
            animation-duration: .3s; }

.card {
  margin-top: 50px;
  background: #eee;
  padding: 3em;
  line-height: 1.5em; }

@media screen and (min-width: 997px) {
  .wrapper {
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex; } }

.details {
  display: -webkit-box;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-box-orient: vertical;
  -webkit-box-direction: normal;
  -webkit-flex-direction: column;
      -ms-flex-direction: column;
          flex-direction: column; }

.colors {
  -webkit-box-flex: 1;
  -webkit-flex-grow: 1;
      -ms-flex-positive: 1;
          flex-grow: 1; }

.product-title, .price, .sizes, .colors,.total-amount {
  text-transform: UPPERCASE;
  font-weight: bold; }

.checked, .price,.total-amount span {
  color: #ff9f1a; }

.product-title, .rating, .product-description, .price, .vote, .sizes {
  margin-bottom: 15px; }

.product-title {
  margin-top: 0; }

.size {
  margin-right: 10px; }
  .size:first-of-type {
    margin-left: 40px; }

.color {
  display: inline-block;
  vertical-align: middle;
  margin-right: 10px;
  height: 2em;
  width: 2em;
  border-radius: 2px; }
  .color:first-of-type {
    margin-left: 20px; }

.add-to-cart, .like {
  background: #ff9f1a;
  padding: 1.2em 1.5em;
  border: none;
  text-transform: UPPERCASE;
  font-weight: bold;
  color: #fff;
  -webkit-transition: background .3s ease;
          transition: background .3s ease; }
  .add-to-cart:hover, .like:hover {
    background: #b36800;
    color: #fff; }

.not-available {
  text-align: center;
  line-height: 2em; }
  .not-available:before {
    font-family: fontawesome;
    content: "\f00d";
    color: #fff; }

.orange {
  background: #ff9f1a; }

.green {
  background: #17a895; }

.blue {
  background: #0076ad; }

.tooltip-inner {
  padding: 1.3em; }

@-webkit-keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }

@keyframes opacity {
  0% {
    opacity: 0;
    -webkit-transform: scale(3);
            transform: scale(3); }
  100% {
    opacity: 1;
    -webkit-transform: scale(1);
            transform: scale(1); } }
</style>
{% endblock bodyblock%}