cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('<int:id>', views.lst_course, name='khoahoc'),
    path('course_details/<int:pk>', views.detail, name='lophoc'),
    path('registered_courses', views.registered_courses, name='registered'),

]

mentor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', include('register.urls'), name="register"),
    path('courses/', include('courses.urls'), name="courses"),
    path('cart/', include('cart.urls'), name="cart"),
    path('orders/', include('orders.urls'), name="orders"),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

courses/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from .myfields import FieldNgayTrongTuan as ntt
import datetime
from embed_video.fields import EmbedVideoField
from django.core.validators import MinValueValidator, MaxValueValidator
# Create your models here.


class Category(models.Model):
    phanloai = models.CharField(max_length=20)

    def __str__(self):
        return str(self.phanloai)


class Course(models.Model):
    ten_khoahoc = models.CharField(max_length=150)
    description = RichTextUploadingField(blank=True)
    course_price1 = models.FloatField(default=500000)
    course_price2 = models.FloatField(default=500000)
    course_start_date = models.DateField(blank=True)
    course_end_date = models.DateField(blank=True)
    photo = models.ImageField(
        upload_to="courses/images", default="courses/images/english-time.jpg")
    category_id = models.ForeignKey(Category, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.ten_khoahoc)


class LopHoc(models.Model):
    ten_lop = models.CharField(max_length=100)
    hinh = models.ImageField(upload_to="courses/images",
                             default="courses/images/course-1.jpg")
    description = RichTextUploadingField(blank=True)
    lophoc_start_date = models.DateField(blank=True, null=True)
    lophoc_end_date = models.DateField(blank=True, null=True)
    price = models.FloatField(default=500000)
    discount = models.FloatField(default=0)
    days1 = ntt(max_length=50, default="Chủ Nhật", blank=True)
    days2 = ntt(max_length=50, default="Chủ Nhật", blank=True)
    days3 = ntt(max_length=50, default="Chủ Nhật", blank=True)
    hours1 = models.TimeField(default=datetime.datetime.now())
    hours2 = models.TimeField(default=datetime.datetime.now())
    course_id = models.ForeignKey(Course, on_delete=models.PROTECT)
    teacher_id = models.ForeignKey(
        "main.Teacher", on_delete=models.PROTECT)

    def __str__(self):
        return str(self.ten_lop)

    def get_price(self):
        price = int(self.price*(100-self.discount)/100)
        return price


class BaiHoc(models.Model):
    ten_bai = models.CharField(max_length=50)
    content = RichTextUploadingField(blank=True)
    lecture = EmbedVideoField(blank=True)
    lophoc_id = models.ForeignKey(LopHoc, on_delete=models.PROTECT)

    def __str__(self):
        return str(self.ten_bai)

courses/views.py
from django.shortcuts import render
import datetime
from . import models
from cart.forms import CartAddProductForm
import re
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.cart import Cart
from orders import models as order_models
from register.views import user_login, User
from django.db.models import Count
from math import ceil

# Create your views here.
category = models.Category.objects.all()
lophoc = models.LopHoc.objects.all()
khoahoc = models.Course.objects.all()
baihoc = models.BaiHoc.objects.all()

now = datetime.datetime.now()


def courses(request):
    if len(khoahoc) > 0:
        lst_lophoc = lophoc.exclude(
            course_id__isnull=True).order_by('ten_lop')

        return render(request, "courses/courses.html", context={'khoahoc': khoahoc, 'lophoc': lophoc, 'lst_lophoc': lst_lophoc, 'today': now, })

    # return render(request, "courses/courses.html", {'dc': dc, })


def lst_course(request, id):
    lst_lophoc = lophoc.filter(course_id=id).order_by('ten_lop')

    return render(request, "courses/courses.html", context={'khoahoc': khoahoc, 'lophoc': lophoc, 'lst_lophoc': lst_lophoc, 'today': now})


def detail(request, pk):
    cart_product_form = CartAddProductForm()
    select_lop = lophoc.get(pk=pk)
    lst_bai = baihoc.filter(lophoc_id=select_lop)

    return render(request, "courses/course_details.html", {'select_lop': select_lop, 'khoahoc': khoahoc, 'lst_bai': lst_bai, 'cart_product_form': cart_product_form, 'today': now})


def registered_courses(request):
    username = request.session.get('username', 0)
    if request.user.is_authenticated:
        user = request.user
    users = order_models.Order.objects.all()
    regis_user = users.filter(username=user.username)
    # print(regis_user)

    items = order_models.OrderItem.objects.all()
    regis_item = items.filter(order__in=regis_user)
    # print(regis_item)
    # print(regis_item.values('id'))

    c = lophoc.filter(id__in=regis_item.values('product_id'))
    num = regis_item.values('product_id').annotate(n=Count('product_id'))
    # print(c.values('ten_lop'))
    zipped_lst = zip(c, num)

    return render(request, "courses/registered_courses.html", {'regis_user': regis_user, 'regis_item': regis_item, 'list': zipped_lst, 'today': now})

courses/templates/courses/course_details.html
{% extends "main/base.html" %}
{% load static %}
{% load embed_video_tags %}

{% block titleblock %}
<title>Thông tin khóa học - LEAP</title>
{% endblock titleblock %}

{% block bodyblock %}
<main id="main">
  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs" data-aos="fade-in">
    <div class="container">
      <h2>Thông tin khóa học</h2>
      <p>
        Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia
        id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam
        aperiam consequatur laboriosam nemo harum praesentium.
      </p>
    </div>
  </div>
  <!-- End Breadcrumbs -->

  <!-- ======= Cource Details Section ======= -->
  <section id="course-details" class="course-details">
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-lg-8">
          <img src="{% static 'main/img/course_details.jpg' %}" class="img-fluid" alt=""/>
          <h3>{{select_lop.ten_lop}}</h3>
          <p>{{select_lop.description|safe}}</p>
        </div>
        <div class="col-lg-4">
          <div class="course-info d-flex justify-content-between align-items-center">
            <h5>Giáo viên</h5>
            <p><a href="#">{{select_lop.teacher_id}}</a></p>
          </div>
          <div class="course-info d-flex justify-content-between align-items-center">
            <h5>Học phí</h5>
            <p>{% load humanize %}{{select_lop.price|floatformat:0|intcomma}} VNĐ</p>
          </div>

          <div class="course-info d-flex justify-content-between align-items-center">
            <h5>Chỗ trống</h5>
            <p>15</p>
          </div>

          <div class="course-info d-flex justify-content-between align-items-center">
            <h5>Giờ học</h5>
            <p>{{select_lop.hours1}} - {{select_lop.hours2}}</p>
            <p style="text-align: right">
              {{select_lop.days1}}<br />
              {{select_lop.days2}}<br />
              {{select_lop.days3}}
            </p>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- End Cource Details Section -->

  <!-- ======= Cource Details Tabs Section ======= -->
  <section id="cource-details-tabs" class="cource-details-tabs">
    <div class="container" data-aos="fade-up">
      <div class="row">
        <div class="col-lg-3">
          <ul class="nav nav-tabs flex-column">
            {% for bai in lst_bai %}
            <li class="nav-item">
              <a class="nav-link {%if forloop.first%}active show{%endif%}" data-bs-toggle="tab" href="#tab-{{forloop.counter}}">{{bai.ten_bai}}</a>
            </li> 
            {% endfor %}
          </ul>
        </div>
        <div class="col-lg-9 mt-4 mt-lg-0">
          <div class="tab-content">
            {% for bai in lst_bai %}
            <div class="tab-pane {%if forloop.first%}active show{%endif%}" id="tab-{{forloop.counter}}">
              <div class="row">
                <div class="col-lg-8 details order-2 order-lg-1">
                  <h4>Nội dung bài học</h4>
                  <p class="fst-italic">{{bai.content|safe}}</p>

                  <p>
                    <a data-bs-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
                      Xem thử bài giảng
                    </a>
                  </p>

                  <div class="collapse" id="collapseExample">
                    <div class="card card-body">
                      {% video bai.lecture%}
                    </div>
                  </div>
                  
                </div>
              </div>
            </div>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <div class="container text-center" data-aos="fade-up" style="margin-top: 30px;">
      <form action="{%url 'cart:cart_add' select_lop.id%}" method="POST">
        {{cart_product_form}}
        {% csrf_token %}
        <input type="hidden" name="quantity" value="1" />
        <button class="btn get-started-btn active-show" type="submit">
          Mua khóa học
        </button>
      </form>
    </div>
  </section>
  <!-- End Cource Details Tabs Section -->
</main>
{% endblock bodyblock %}

courses/templates/courses/courses.html
{% extends "main/base.html" %}
{% load static %}

{% block titleblock %}
<title>LEAP - Danh sách khóa học</title>
{% endblock titleblock %}

{% block bodyblock %}
<main id="main" data-aos="fade-in">

  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs">
    <div class="container">
      <h2>Các khóa học</h2>
      <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
    </div>
  </div><!-- End Breadcrumbs -->
  
  <!-- ======= Courses Section ======= -->
  <section id="courses" class="courses">
    <div class="container" data-aos="fade-up">

      {% if khoahoc %}
      <div class="dropdown" style="margin-bottom: 10px;">
        <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          Chọn khóa học
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><a class="dropdown-item" href="{% url 'courses:courses' %}">Tất cả khóa học</a></li>
          {% for item in khoahoc %}
          <li><a class="dropdown-item" href="{% url 'courses:khoahoc' item.id %}">{{item.ten_khoahoc}}</a></li>
          {% endfor %}
        </ul>
      </div>
      {% endif %}

      <div class="row" data-aos="zoom-in" data-aos-delay="100">
        {% if lst_lophoc %}
        {% for lop in lst_lophoc %}
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
          <div class="course-item">
            {% for item in lst %}
              <div class="discount-label red"><span>-{{item.discount}}%</span></div>
            {% endfor %}
            <img src="{{lop.hinh.url}}" class="img-fluid" alt="..." style="height: 300px;width:auto">
            <div class="course-content">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <h4>{{lop.course_id}}</h4>
                <p class="price">{% load humanize %}{{lop.get_price|floatformat:0|intcomma}} VNĐ</p>
              </div>
              <h3><a href="{% url 'courses:lophoc' lop.pk%}">{{lop.ten_lop}}</a></h3>
              <p>{{lop.description|safe}}</p>
              
              <div class="trainer d-flex justify-content-between align-items-center">
                <div class="trainer-profile d-flex align-items-center">
                  <img src="{% static 'main/img/trainers/trainer-2.jpg' %}" class="img-fluid" alt="">
                  <span>{{lop.teacher_id}}</span>
                </div>
                <div class="trainer-rank d-flex align-items-center">
                  <i class="bx bx-user"></i>&nbsp;50
                  &nbsp;&nbsp;
                  <i class="bx bx-heart"></i>&nbsp;65
                </div>
              </div>
            </div>
          </div>
        </div> <!-- End Course Item-->
        {% endfor %}
        {% endif %}
      </div>

    </div>
  </section><!-- End Courses Section -->

</main><!-- End #main -->
{% endblock bodyblock %}

courses/templates/courses/registered_courses.html
{% extends "main/base.html" %}
{% load static %}

{% block titleblock %}
<title>LEAP - Khóa đã đăng ký</title>
{% endblock %}

{% block bodyblock %}
<main id="main" data-aos="fade-in">

  <!-- ======= Breadcrumbs ======= -->
  <div class="breadcrumbs">
    <div class="container">
      <h2>Các khóa mà bạn đã đăng ký</h2>
      <p>Sau đây là danh sách các khóa học mà bạn <b> {{user.first_name}} {{user.last_name}} </b> đã đăng ký tại trung tâm.</p>
    </div>
  </div><!-- End Breadcrumbs -->
  
  
  <!-- ======= Courses Section ======= -->
  <section id="courses" class="courses">
    <div class="container" data-aos="fade-up">
      <div class="row" data-aos="zoom-in" data-aos-delay="100">
        {% for item,n in list %}
        <div class="col-lg-4 col-md-6 d-flex align-items-stretch">
          <div class="course-item">
            <img src="{% static 'main/img/course-1.jpg' %}" class="img-fluid" alt="...">
            <div class="course-content">
              <div class="d-flex justify-content-between align-items-center mb-3">
                <h4>{{item.course_id}}</h4>
                <p class="price">{% load humanize %}{{item.price|floatformat:0|intcomma}} VNĐ</p>
              </div>
              <h3 class="mb-3">{{item.ten_lop}}</h3>
              <h6><strong>Ngày học:</strong> {{item.days1}}, {{item.days2}}, {{item.days3}}</h6>
              <h6><strong>Lúc:</strong> {{item.hours1}} - {{item.hours2}}</h6>
              <h6>Số khóa đăng ký: {{n.n}}</h6>
              <div class="trainer d-flex justify-content-between align-items-center">
                <div class="trainer-profile d-flex align-items-center">
                  <img src="{% static 'main/img/trainers/trainer-2.jpg' %}" class="img-fluid" alt="">
                  <span>Giáo viên giảng dạy: {{item.teacher_id}}</span>
                </div>
              </div>
            </div>
          </div>
        </div> <!-- End Course Item-->
        {% endfor %}
      </div>
    </div>
  </section><!-- End Courses Section -->
</main><!-- End #main -->
{% endblock %}



<section class="shop checkout section">
  <div class="container" style="margin-top: 70px; max-height: 500px">
    <div class="row">
      <div class="col-lg-8 col-12">
        <div class="checkout-form">
          <h2>Cảm ơn quý khách</h2>
          <p>
            Quý khách <b> {{user.first_name}} {{user.last_name}} </b> đã đăng ký khóa học thành công.
          </p>
        </div>
      </div>
      <div class="col-lg-4 col-12">
        <div class="order-details">
          <!-- Order Widget -->
          <div class="single-widget">
            <h2>THÔNG TIN LỚP HỌC</h2>
            <div class="content">
              <ul>
                {% for item in c %}
                  <li>Tên lớp: {{item.ten_lop}}</li>
                  <li>Ngày học: {{item.days1}}, {{item.days2}}, {{item.days3}}</li>
                  <li>Lúc: {{item.hours1}} - {{item.hours2}}</li>
                  <li>Mã zoom: </li>
                {% endfor %}
                
              </ul>
            </div>
            <a href="{% url 'main:index.html'%}" class="btn-get-started"
              >Về trang chủ</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>