cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'

urlpatterns = [
    path('', views.courses, name='courses'),
    path('<int:id>', views.lst_course, name='khoahoc'),
    path('course_details/<int:pk>', views.detail, name='lophoc'),
    path('registered_courses', views.registered_courses, name='registered'),

]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index.html'),
    path('about/', views.about, name='about.html'),
    path('contact/', views.contact, name='contact.html'),
    path('trainers/', views.trainers, name='trainers.html'),
]

mentor/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('django.contrib.auth.urls')),
    path('register/', include('register.urls'), name="register"),
    path('courses/', include('courses.urls'), name="courses"),
    path('cart/', include('cart.urls'), name="cart"),
    path('orders/', include('orders.urls'), name="orders"),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from courses.models import models
import datetime
from ckeditor_uploader.fields import RichTextUploadingField
from phone_field import PhoneField
from django.contrib.auth.models import User
# Create your models here.

# Teacher Models


class Teacher(models.Model):
    description = models.CharField(max_length=300)
    photo = models.ImageField(upload_to="main/images",
                              default="main/images/trainer-2.jpg")
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)

    def __str__(self):
        return str(self.first_name)


# Student Models


class Student(models.Model):
    date_birth = models.DateField(blank=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50, blank=True)
    city = models.CharField(max_length=100)
    street = models.CharField(max_length=100)
    email = models.EmailField(blank=True)
    phone = models.CharField(max_length=15)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    class_id = models.ForeignKey(
        "courses.LopHoc", on_delete=models.CASCADE)

    def __str__(self):
        return str(self.first_name)


# Payment Models
class PaymentMethod(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Payment(models.Model):
    payment_date = models.DateTimeField()
    amount = models.FloatField()
    payment_method_id = models.ForeignKey(
        PaymentMethod, on_delete=models.PROTECT)
    status = models.CharField(max_length=50)
    student_id = models.ForeignKey(Student, on_delete=models.PROTECT)
    class_id = models.ForeignKey("courses.LopHoc", on_delete=models.PROTECT)

    def __str__(self):
        return self.payment_date


class Contact(models.Model):
    name = models.CharField(max_length=150)
    email = models.EmailField()
    phone_number = models.CharField(max_length=20, null=True)
    subject = models.CharField(max_length=264)
    message = models.TextField()

    def __str__(self):
        return self.name + ", " + self.subject


class User(models.Model):
    username = models.CharField(max_length=15, unique=True)
    password = models.CharField(max_length=32)
    fullname = models.CharField(max_length=100, unique=False)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    address = models.CharField(
        max_length=500, unique=False, default='', blank=True)

    def __str__(self):
        return self.username

main/forms.py
from django import forms
from . import models
from django.core.validators import RegexValidator

phone_validator = RegexValidator(
    r"((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))", "Your phone number must be (xxx)xxxxxxxxx or 0xxxxxxxxx!")


class UserForm(forms.ModelForm):
    password = forms.CharField(
        max_length=150, label='Password', widget=forms.PasswordInput())
    confirm = forms.CharField(
        max_length=150, label='Confirm', widget=forms.PasswordInput())
    # set_password=password

    class Meta():
        model = models.User
        fields = ('username', 'email', 'password')


class FormContact(forms.ModelForm):
    name = forms.CharField(max_length=150, label='Name', widget=forms.TextInput(attrs={
                           'placeholder': 'Nhập tên của bạn', 'class': 'form-control fh5co_contact_text_box'}))
    phone_number = forms.CharField(max_length=20, label='Phone', validators=[phone_validator], widget=forms.TextInput(
        attrs={'placeholder': 'Số điện thoại',
               'class': 'form-control fh5co_contact_text_box',
               'pattern': '((\([0-9]{3}\)[0-9]{9,15})|([0-9]{10,15}))',
               'title': 'Số điện thoại phải có dạng (xxx)xxxxxxxxx or 0xxxxxxxxx'}))
    email = forms.EmailField(label='Email', widget=forms.TextInput(
        attrs={'placeholder': 'Email', 'class': 'form-control fh5co_contact_text_box'}))
    subject = forms.CharField(label='Subject', widget=forms.TextInput(
        attrs={'placeholder': 'Tiêu đề', 'class': 'form-control fh5co_contact_text_box'}))
    message = forms.CharField(widget=forms.Textarea(
        attrs={'placeholder': 'Điền tin nhắn', 'class': 'form-control fh5co_contacts_message'}))

    class Meta:
        model = models.Contact
        fields = '__all__'

main/views.py
from django.shortcuts import render, HttpResponse
from . import models as main_models
from courses import models as course_models
# from courses import views
from register.views import register, user_login, user_logout
from . import forms
import datetime
# from . import forms
import re
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from mentor.settings import EMAIL_HOST_USER
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
import feedparser


# Create your views here.
# from courses.models import *


def index(request):
    now = datetime.datetime.now()
    category = course_models.Category.objects.all()
    khoahoc = course_models.Course.objects.all()
    lst_khoahoc = khoahoc[:3]
    teacher = main_models.Teacher.objects.all()
    lst_teacher = teacher[:3]

    return render(request, "main/index.html", {'lst_khoahoc': lst_khoahoc, 'lst_teacher': lst_teacher, 'category': category, 'today': now})


def about(request):
    return render(request, "main/about.html")


def trainers(request):
    teacher = main_models.Teacher.objects.all()
    lst_teacher = teacher[:3]
    return render(request, "main/trainers.html", {'lst_teacher': lst_teacher})


def subscribe(request):
    now = datetime.datetime.now()
    last_visit = request.session.get('last_visit', False)
    username = request.session.get('username', 0)
    if request.method == 'POST':
        email_address = request.POST.get("email")
        subject = 'Welcome to LEAP English website'
        message = 'Hope you enjoy!'
        recepient = str(email_address)
        # send_mail(subject, message, EMAIL_HOST_USER, [recipient], fail_silently=False)

        html_content = '<h2 style="color:blue"><i>Dear Reader,</i></h2>'\
            + '<p>Welcome to <strong>LEAP English</strong> website.</p>' \
            + '<h4 style="color:red">' + message + '</h4>'

        msg = EmailMultiAlternatives(
            subject, message, EMAIL_HOST_USER, [recepient])
        msg.attach_alternative(html_content, "text/html")
        msg.send()

        # send_mail(subject, message, EMAIL_HOST_USER,
        #           [recepient], fail_silently=False)

        result = "Our email was sent to your mail box. Thank you."

        return render(request, 'main/index.html', {'today': now, 'username': username, 'last_visit': last_visit, 'result': result, })
    return render(request, 'main/index.html', {'today': now, 'username': username, 'last_visit': last_visit})


def contact(request):
    now = datetime.datetime.now()
    result = ''
    success = False
    form = forms.FormContact()
    if request.method == 'POST':
        result = "Form có post"
        form = forms.FormContact(request.POST, main_models.Contact)
        result = "Form có Contact"
        # them validation cho from
        if form.is_valid():
            result = "Form đã valid!"
            request.POST._mutable = True
            post = form.save(commit=False)
            post.name = form.cleaned_data['name']
            post.phone_number = form.cleaned_data['phone_number']
            post.email = form.cleaned_data['email']
            post.password = form.cleaned_data['subject']
            post.password = form.cleaned_data['message']
            post.save()
            result = "Cảm ơn bạn đã liên lạc. Chúng tôi sẽ phản hồi sớm nhất có thể."
            success = [True if result != '' else False]
    else:
        form = forms.FormContact()

    last_visit = request.session.get('last_visit', False)

    return render(request, "main/contact.html", {'today': now, 'form': form, 'result': result, 'success': success})

main/templates/main/about.html
{% extends "main/base.html" %}
{% load static %}

{% block titleblock %}
<title>LEAP - Về chúng tôi</title>
{% endblock titleblock %}

{% block bodyblock %}
<main id="main">
<!-- ======= Breadcrumbs ======= -->
<div class="breadcrumbs" data-aos="fade-in">
  <div class="container">
    <h2>Về chúng tôi</h2>
    <p>Est dolorum ut non facere possimus quibusdam eligendi voluptatem. Quia id aut similique quia voluptas sit quaerat debitis. Rerum omnis ipsam aperiam consequatur laboriosam nemo harum praesentium. </p>
  </div>
</div><!-- End Breadcrumbs -->

<!-- ======= About Section ======= -->
<section id="about" class="about">
  <div class="container" data-aos="fade-up">

    <div class="row">
      <div class="col-lg-6 order-1 order-lg-2" data-aos="fade-left" data-aos-delay="100">
        <img src="{% static 'main/img/about.jpg' %}" class="img-fluid" alt="">
      </div>
      <div class="col-lg-6 pt-4 pt-lg-0 order-2 order-lg-1 content">
        <h3>Voluptatem dignissimos provident quasi corporis voluptates sit assumenda.</h3>
        <p class="fst-italic">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore
          magna aliqua.
        </p>
        <ul>
          <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat.</li>
          <li><i class="bi bi-check-circle"></i> Duis aute irure dolor in reprehenderit in voluptate velit.</li>
          <li><i class="bi bi-check-circle"></i> Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate trideta storacalaperda mastiro dolore eu fugiat nulla pariatur.</li>
        </ul>
        <p>
          Ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate
        </p>

      </div>
    </div>

  </div>
</section><!-- End About Section -->

<!-- ======= Counts Section ======= -->
<section id="counts" class="counts section-bg">
  <div class="container">

    <div class="row counters">

      <div class="col-lg-3 col-6 text-center">
        <span data-purecounter-start="0" data-purecounter-end="1232" data-purecounter-duration="1" class="purecounter"></span>
        <p>Students</p>
      </div>

      <div class="col-lg-3 col-6 text-center">
        <span data-purecounter-start="0" data-purecounter-end="64" data-purecounter-duration="1" class="purecounter"></span>
        <p>Courses</p>
      </div>

      <div class="col-lg-3 col-6 text-center">
        <span data-purecounter-start="0" data-purecounter-end="42" data-purecounter-duration="1" class="purecounter"></span>
        <p>Events</p>
      </div>

      <div class="col-lg-3 col-6 text-center">
        <span data-purecounter-start="0" data-purecounter-end="15" data-purecounter-duration="1" class="purecounter"></span>
        <p>Trainers</p>
      </div>

    </div>

  </div>
</section><!-- End Counts Section -->

<!-- ======= Testimonials Section ======= -->
<section id="testimonials" class="testimonials">
  <div class="container" data-aos="fade-up">

    <div class="section-title">
      <h2>Testimonials</h2>
      <p>What are they saying</p>
    </div>

    <div class="testimonials-slider swiper" data-aos="fade-up" data-aos-delay="100">
      <div class="swiper-wrapper">

        <div class="swiper-slide">
          <div class="testimonial-wrap">
            <div class="testimonial-item">
              <img src="{% static 'main/img/testimonials/testimonials-1.jpg' %}" class="testimonial-img" alt="">
              <h3>Saul Goodman</h3>
              <h4>Ceo &amp; Founder</h4>
              <p>
                <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                Proin iaculis purus consequat sem cure digni ssim donec porttitora entum suscipit rhoncus. Accusantium quam, ultricies eget id, aliquam eget nibh et. Maecen aliquam, risus at semper.
                <i class="bx bxs-quote-alt-right quote-icon-right"></i>
              </p>
            </div>
          </div>
        </div><!-- End testimonial item -->

        <div class="swiper-slide">
          <div class="testimonial-wrap">
            <div class="testimonial-item">
              <img src="{% static 'main/img/testimonials/testimonials-2.jpg' %}" class="testimonial-img" alt="">
              <h3>Sara Wilsson</h3>
              <h4>Designer</h4>
              <p>
                <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                Export tempor illum tamen malis malis eram quae irure esse labore quem cillum quid cillum eram malis quorum velit fore eram velit sunt aliqua noster fugiat irure amet legam anim culpa.
                <i class="bx bxs-quote-alt-right quote-icon-right"></i>
              </p>
            </div>
          </div>
        </div><!-- End testimonial item -->

        <div class="swiper-slide">
          <div class="testimonial-wrap">
            <div class="testimonial-item">
              <img src="{% static 'main/img/testimonials/testimonials-3.jpg' %}" class="testimonial-img" alt="">
              <h3>Jena Karlis</h3>
              <h4>Store Owner</h4>
              <p>
                <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                Enim nisi quem export duis labore cillum quae magna enim sint quorum nulla quem veniam duis minim tempor labore quem eram duis noster aute amet eram fore quis sint minim.
                <i class="bx bxs-quote-alt-right quote-icon-right"></i>
              </p>
            </div>
          </div>
        </div><!-- End testimonial item -->

        <div class="swiper-slide">
          <div class="testimonial-wrap">
            <div class="testimonial-item">
              <img src="{% static 'main/img/testimonials/testimonials-4.jpg' %}" class="testimonial-img" alt="">
              <h3>Matt Brandon</h3>
              <h4>Freelancer</h4>
              <p>
                <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                Fugiat enim eram quae cillum dolore dolor amet nulla culpa multos export minim fugiat minim velit minim dolor enim duis veniam ipsum anim magna sunt elit fore quem dolore labore illum veniam.
                <i class="bx bxs-quote-alt-right quote-icon-right"></i>
              </p>
            </div>
          </div>
        </div><!-- End testimonial item -->

        <div class="swiper-slide">
          <div class="testimonial-wrap">
            <div class="testimonial-item">
              <img src="{% static 'main/img/testimonials/testimonials-5.jpg' %}" class="testimonial-img" alt="">
              <h3>John Larson</h3>
              <h4>Entrepreneur</h4>
              <p>
                <i class="bx bxs-quote-alt-left quote-icon-left"></i>
                Quis quorum aliqua sint quem legam fore sunt eram irure aliqua veniam tempor noster veniam enim culpa labore duis sunt culpa nulla illum cillum fugiat legam esse veniam culpa fore nisi cillum quid.
                <i class="bx bxs-quote-alt-right quote-icon-right"></i>
              </p>
            </div>
          </div>
        </div><!-- End testimonial item -->

      </div>
      <div class="swiper-pagination"></div>
    </div>

  </div>
</section><!-- End Testimonials Section -->
</main>
{% endblock bodyblock %}

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  {% block titleblock %}
  {% endblock titleblock %}
  
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'main/img/favicon.png' %}" rel="icon">
  <link href="{% static 'main/img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Tahoma:300,300i,400,400i,600,600i,700,700i|Verdana:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'main/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
  <link href="{% static 'main/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'main/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'main/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'main/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'main/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'main/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="{% static 'main/css/style.css' %}" rel="stylesheet">
</head>

<body>
  {% block header %}
  <!-- ======= Header ======= -->
  <header id="header" class="fixed-top">
    <div class="container d-flex align-items-center">

      <h1 class="logo me-auto"><a href="{% url 'main:index.html'%}">LEAP</a></h1>
      <!-- Uncomment below if you prefer to use an image logo -->
      <!-- <a href="index.html" class="logo me-auto"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->

      <nav id="navbar" class="navbar order-last order-lg-0">
        <ul>
          <li><a class="active" href="{% url 'main:index.html'%}">Trang chủ</a></li>
          <li><a href="{% url 'main:about.html'%}">Về chúng tôi</a></li>
          <li><a href="{% url 'courses:courses'%}">Khóa học</a></li>
          {% if user.is_authenticated %}
          <li><a href="{% url 'courses:registered'%}">Khóa đã đăng ký</a></li>
          {% endif %}
          <li><a href="{% url 'main:trainers.html'%}">Giáo viên</a></li>
          <li><a href="{% url 'main:contact.html'%}">Liên hệ</a></li>
          {% if user.is_authenticated %}
          <li><a href="#">Xin chào {{user.last_name}}</a></li>
          {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav>
      {% if user.is_authenticated %}
      <!-- .navbar -->
      <a href="/logout" class="get-started-btn">Đăng xuất</a>
      {%else%}
      <div class="dropdown">
        <a class="get-started-btn dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
          Đăng ký
        </a>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
          <li><a class="dropdown-item" href="/register">Đăng ký</a></li>
          <li><a class="dropdown-item" href="/login">Đăng nhập</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </header>
  <!-- End Header -->
  {% endblock header %}

  {% block heroblock %}
  {% endblock heroblock %}


  {% block bodyblock %}
  {% endblock bodyblock %}


  <!-- ======= Footer ======= -->
  <footer id="footer">

    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h3>LEAP</h3>
            <p>
              15/36B Nguyễn Thị Phố <br>
              Tân Đông Hiệp, Dĩ An<br>
              Bình Dương, Việt Nam <br><br>
              <strong>Điện thoại:</strong> 0963 645 899<br>
              <strong>Email:</strong> vuhien694@gmail.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Liên kết hữu ích</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Trang chủ</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Về chúng tôi</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Dịch vụ</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Điều khoản dịch vụ</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Chính sách quyền riêng tư</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Dịch vụ của chúng tôi</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Tiếng Anh trẻ em</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Tiếng Anh phổ thông</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Tiếng Anh giao tiếp</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Dịch thuật</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Luyện thi IELTS</a></li>
            </ul>
          </div>

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Đăng ký tin mới</h4>
            <p>Đăng ký để nhận tin tức mới nhất từ chúng tôi.</p>
            <form action="" method="post">
              {% csrf_token %}
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>LEAP</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/mentor-free-education-bootstrap-theme/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="https://www.facebook.com/leap.tienganhtreem/" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="youtube"><i class="bx bxl-youtube"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div>
  </footer><!-- End Footer -->


  <!-- Messenger Plugin chat Code -->
  <div id="fb-root"></div>

  <!-- Your Plugin chat code -->
  <div id="fb-customer-chat" class="fb-customerchat">
  </div>

  <script>
    var chatbox = document.getElementById('fb-customer-chat');
    chatbox.setAttribute("page_id", "103572598059552");
    chatbox.setAttribute("attribution", "biz_inbox");
  </script>

  <!-- Your SDK code -->
  <script>
    window.fbAsyncInit = function() {
      FB.init({
        xfbml            : true,
        version          : 'v14.0'
      });
    };

    (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));
  </script>



  <div id="preloader"></div>
  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="{% static 'main/vendor/purecounter/purecounter.js' %}"></script>
  <script src="{% static 'main/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'main/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'main/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'main/vendor/php-email-form/validate.js' %}"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'main/js/main.js' %}"></script>

</body>

</html>